<?php
/**
 * @file
 */


/**
 * Implements hook_block_info().
 */
function starter_demo_block_info() {
  $blocks['starter_demo'] = array(
    'info' => t('[Custom] Example block'),
    'cache' => DRUPAL_NO_CACHE
  );

  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function starter_demo_block_view($delta = '') {
  $block = array();

  switch ($delta) {
    case 'starter_demo':
      global $user;
      $name = $user->uid ? $user->name : 'Anonymous';
      $block['subject'] = t('Drupal CI');
      $block['content'] = t('<p>Hi @name! This is example block content</p>', array('@name' => $name));
      break;

  }
  return $block;
}

/**
 * Implements hook_menu().
 */
function starter_demo_menu() {
  $items['example'] = array(
    'title' => 'Example',
    'page callback' => 'starter_demo_page',
    'access callback' => TRUE,
    'type' => MENU_NORMAL_ITEM,
    'menu_name' => 'main-menu',
    'weight' => 10,
  );

  return $items;
}

/**
 * Return content example page.
 */
function starter_demo_page() {
  return '<p>But I must explain to you how all this mistaken idea of denouncing pleasure and praising pain was born and I will give you a complete account of the system, and expound the actual teachings of the great explorer of the truth, the master-builder of human happiness.</p><p>No one rejects, dislikes, or avoids pleasure itself, because it is pleasure, but because those who do not know how to pursue pleasure rationally encounter consequences that are extremely painful. Nor again is there anyone who loves or pursues or desires to obtain pain of itself, because it is pain, but because occasionally circumstances occur in which toil and pain can procure him some great pleasure. To take a trivial example, which of us ever undertakes laborious physical exercise, except to obtain some advantage from it? But who has any right to find fault with a man who chooses to enjoy a pleasure that has no annoying consequences, or one who avoids a pain that produces no resultant pleasure?</p>';
}
