<?php
/**
 * @file
 */


/**
 * Implements hook_block_info().
 */
function ffwvn_demo_block_info() {
  $blocks['ffwvn_demo'] = array(
    'info' => t('Example block'),
    'cache' => DRUPAL_NO_CACHE
  );

  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function ffwvn_demo_block_view($delta = '') {
  $block = array();

  switch ($delta) {
    case 'ffwvn_demo':
      $block['subject'] = t('Drupal CI');
      $block['content'] = '<p>Hello Drupal - CI - Docker</p>';
      break;

  }
  return $block;
}
